[package]
name = "recreate"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
pretty_assertions = "1.4"
tempfile = "3.13.0"
fuel-asm = "0.57.1"
fuels = "0.66.5"
tokio = { version = "1.40.0", features = ["full"] }
